#Base:
FROM python
LABEL version="latest" maintainer="TST Automation Team"

#Update na Imagem
RUN apt-get update

#robotframework e seleniumlibrary
RUN pip install robotframework
RUN pip install robotframework-seleniumlibrary

RUN python3 -m pip install robotframework && pip install robotframework-requests &&  pip install robotframework-selenium2library \
    && pip install xvfbwrapper && pip install robotframework-xvfb && pip install certifi && pip install asn1crypto \
    && pip install bcrypt && pip install robotframework-sshlibrary && pip install cryptography && pip install pyOpenSSL \
    && pip install idna && pip install requests[security]

#Chrome e Chromedriver:
RUN apt-get install -y xvfb
RUN apt-get install -y zip
RUN apt-get install -y wget
RUN apt-get install ca-certificates
RUN apt-get install -y libnss3-dev
RUN apt-get install -y libxss1
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
RUN apt-get install -y tzdata
RUN apt-get install -y libappindicator3-1
RUN apt-get install -y libindicator7
RUN apt-get install -y gconf-service
RUN apt-get install -y libgconf-2-4
RUN apt-get install -y libpango1.0-0
RUN apt-get install -y xdg-utils
RUN apt-get install -y fonts-liberation
RUN apt-get install -y xvfb wget ca-certificates libasound2 libatk-bridge2.0-0 libatk1.0-0 \
       libatspi2.0-0 libcups2 libdbus-1-3 libgbm1 libgtk-3-0 libnspr4 libnss3 \
       libxcomposite1 libxkbcommon0 libxrandr2 ntpdate openssl
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome*.deb \
    && rm google-chrome*.deb \
    && wget -q https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip \
    && unzip chromedriver_linux64.zip \
    && rm chromedriver_linux64.zip \
    && mv chromedriver /usr/local/bin \
    && chmod +x /usr/local/bin/chromedriver

RUN pip install paramiko && pip install PyVISA && pip install PyVISA-py
RUN pip install PyJWT==1.7.1
RUN pip install robotframework-pythonlibcore
#Sem necessidade:
RUN mkdir /results
ENTRYPOINT ["bash"]
